### ISSUE TITLE
Make js optional

### ISSUE THREAD

**Issue by fatih** [avianto/hugo-kiera#1]
Hi,

Awesome theme, thank you very much. I'm migrating my blog post to Hugo and going to use this theme. My current blog is here: arslan.io

I saw this:
> Adding some user-oriented behavior using JavaScripts.

Just wanted to add if you can make this optional. This theme is super fast, and would prefer if you don't bloat it going forward. Just an opinion. Thanks!

**Comment by avianto** [comment]
That's what I have in mind, might put it as a param in config.toml to switch JavaScript enhancement on/off. Appreciate the input!
