### ISSUE TITLE
Add image preview to main page

### ISSUE THREAD

**Issue by fatih** [avianto/hugo-kiera#2]
Hi,

Is there a way to add small images to the main page?  For example for my current blog in https://arslan.io I use many small images as I like photos a lot.

**Comment by avianto** [comment]
I have another theme in development for that kind of layout, it will be a slight fork of Kiera. For Kiera, I like to keep the main page as clean as possible. Not sure when I will release it though but it will not be too hard to change from Kiera to the new theme (it will still use the same content concept)

**Comment by avianto** [comment]
Hi @fatih,

I just realize you can actually show image on the main page by put the image tag first on the entry and use ` instead of relying on auto summary. The setback is the image size is as big as you set in the main entry, but that's the best this theme can do right now.
