### ISSUE TITLE
Update font 

### ISSUE THREAD

**Issue by ahmadihamid** [avianto/hugo-kiera#26]
I need some font that not supported in this fontawesome version, so how do I upgrade it?

**Comment by funkydan2** [comment]
I've got fontawesome 5 working [in my fork](https://github.com/funkydan2/hugo-kiera) of kiera. Feel free fork or clone my repo.

**Comment by ahmadihamid** [comment]
thanks @funkydan2, but could you tell me where's the CDN config for the font?

**Comment by funkydan2** [comment]
`layouts/partials/header_includes.html`

You also need to change `layouts/partials/header.html` for social icons to work with FA5.
