### ISSUE TITLE
Consider using .Site.RegularPages

### ISSUE THREAD

**Issue by bep** [avianto/hugo-kiera#3]
https://github.com/avianto/hugo-kiera/blob/a403b6347cb0e2012da35fc811c7a95c0d8402ca/layouts/index.html#L5

Ref. your home page template. I think what most people expect is that you list only "regular pages" on the home page, so I would consider replacing `.Data.Pages` with `.Site.RegularPages` in that particular template.

**Comment by avianto** [comment]
Thank you for the suggestion! I was not sure choosing between `Site.RegularPage` and `.Data.Pages` but your input made it clear for me now. Implemented.
