### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by rbucker** [avianto/hugo-kiera#36]
I tried to deploy on openbsd 6.6 and received an out of memory error.

**Comment by funkydan2** [comment]
Hi @rbucker, 

Although 'out of memory' could be a problem with a theme, I wonder whether it's something particular to your setup, or even possibly a problem with Hugo.

I recommend starting a thread on the [Hugo Discourse](https://discourse.gohugo.io) and posting the error log you get as well as a link to your site's code repository. (I'm pretty active the forum.)

If you're sure it's a problem with the theme (i.e. you've used the same content with another theme without any problems) then post the error log and a link to your repository here so we can work out what it is about this theme which is causing the issue.

**Comment by funkydan2** [comment]
After posting this, I realised which repository you've raised the issue on.

I also recommend using [my fork](https://github.com/funkydan2/hugo-kiera) of this theme. (As per [this issue]https://github.com/avianto/hugo-kiera/issues/34).)

**Comment by rbucker** [comment]
Thanks.
