### ISSUE TITLE
[Question] Pagination in tags

### ISSUE THREAD

**Issue by yamila-moreno** [avianto/hugo-kiera#7]
Hi! I'm trying to migrate my blog to this theme (simple and beautiful, BTW!) and there is a behaviour I don't understand, and I don't find in the documentation.

In the "/tags" url I can see all the tags in a single page, but at the bottom, the pagination is displayed (see screenshot). Is this a bug or just a feature I don't understand? Any hint will be very appreciated! :D 

Thanks!

![pagination](https://user-images.githubusercontent.com/3340793/33038541-4b7a156a-ce35-11e7-9602-2d345e2dcd82.png)

**Comment by avianto** [comment]
Hi, thanks for trying the theme!

About the /tags url, I mentioned it in the last part of README (TO DO):

> /layout/_default/terms.html needs some works, it functions now, barely.

So yeah, it's basically an 'expected' bug. I'll remove the paging page for now until I can figure out what to do with that page.

**Comment by yamila-moreno** [comment]
Hi @avianto thanks for your answer and for the quick fix!
